AllCops:
  NewCops: disable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'lib/mongo_trails/mongo_support/version.rb'
    - 'test/**/*'

Metrics/MethodLength:
  Exclude:
    - 'test/**/*'
